### ISSUE TITLE
Modification in interface

### ISSUE THREAD

**Issue by meetxpress** [Corona-Media/corona-media.github.io#31]
Modifications like alignment, spacing, content representation, and so on.

**Comment by Ms3105** [comment]
I want to resolve this  issue

**Comment by meetxpress** [comment]
Yeah sure, I am working on this. I have also created a PR related to this. PR#32. Can you suggest more if is there anything in your mind? It would be great.

**Comment by Ms3105** [comment]
I think first you have to think about logo, which would be related to site

**Comment by meetxpress** [comment]
Yes, we should. Also, refer to the website and think about the changes for those things which are on the website.

**Comment by ramkrishn123** [comment]
I would like to contribute.
