### ISSUE TITLE
A Logo for the Website

### ISSUE THREAD

**Issue by meetxpress** [Corona-Media/corona-media.github.io#33]
A logo is also required for the website. Share your ideas.

**Comment by IlanLuci** [comment]
Yes agreed! Maybe with a COVID-19 Germ and something to represent activities for kids. Maybe a book or something IDK.

**Comment by meetxpress** [comment]
Can you elaborate more?

**Comment by IlanLuci** [comment]
I don't really have any very specific ideas

**Comment by ramkrishn123** [comment]
I want to contribute.

**Comment by meetxpress** [comment]
is there anything in your mind?
